// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEh3XW5I_iOEoe0XAo5F0kE6qyrgjHMBA',
    appId: '1:794390397400:web:e3d7a360c7a6bdaa9df2ad',
    messagingSenderId: '794390397400',
    projectId: 'blog-app-6258c',
    authDomain: 'blog-app-6258c.firebaseapp.com',
    storageBucket: 'blog-app-6258c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdDxWavMpNFSd7DAd1BJ8YSAnc7cGn6YY',
    appId: '1:794390397400:android:5f0777ff08a6748f9df2ad',
    messagingSenderId: '794390397400',
    projectId: 'blog-app-6258c',
    storageBucket: 'blog-app-6258c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVMeac-91phFN8sq3REQAE-5w0rh5Fvz0',
    appId: '1:794390397400:ios:5b72366d3a0ebffa9df2ad',
    messagingSenderId: '794390397400',
    projectId: 'blog-app-6258c',
    storageBucket: 'blog-app-6258c.appspot.com',
    iosBundleId: 'com.example.blogapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVMeac-91phFN8sq3REQAE-5w0rh5Fvz0',
    appId: '1:794390397400:ios:5b72366d3a0ebffa9df2ad',
    messagingSenderId: '794390397400',
    projectId: 'blog-app-6258c',
    storageBucket: 'blog-app-6258c.appspot.com',
    iosBundleId: 'com.example.blogapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEh3XW5I_iOEoe0XAo5F0kE6qyrgjHMBA',
    appId: '1:794390397400:web:0a760a2ff5ce409a9df2ad',
    messagingSenderId: '794390397400',
    projectId: 'blog-app-6258c',
    authDomain: 'blog-app-6258c.firebaseapp.com',
    storageBucket: 'blog-app-6258c.appspot.com',
  );
}
